server:
  port: 9093
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    name: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: root
    driverClassName: org.postgresql.Driver
jwt:
  auth:
    app: react-java-project
    secret_key: reactjava@123
    expires_in: 3600
  secret: javainuse
